### ISSUE TITLE
clappr template error after building 

### ISSUE THREAD

**Issue by tarkanlar** [thiagopnts/clappr-watermark#1]
Uncaught TypeError: (0 , _clappr.template) is not a function  watermark.js:57

**Comment by thiagopnts** [comment]
Sorry, I forgot to mention, its depending on clappr's master. This is going to work fine in clappr's next release(0.2.14)
